# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: isort
      - task: black
      - task: mypy

  isort:
    cmds:
      - poetry run isort src/

  black:
    cmds:
      - poetry run black src/

  mypy:
    cmds:
      - poetry run mypy src/

  test:
    cmds:
      - poetry run pytest

  run:
    cmds:
      - poetry run python src/main.py
